### PR TITLE
Example

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Level 6*

## Solution

- *Apply example_ynh*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by rndmh3ro** [comment]
Hey @yalh76,

thanks for doing this!

However you cannot update the version from 4 to 5 as there is no upgrade-path. One needs to install invoiceninja 4 and 5 and run a migration. That's why https://github.com/YunoHost-Apps/invoiceninja5_ynh exists. However I don't have much spare time right now to work on this.

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
> 
> 
> Hey @yalh76,
> 
> thanks for doing this!
> 
> However you cannot update the version from 4 to 5 as there is no upgrade-path. One needs to install invoiceninja 4 and 5 and run a migration. That's why https://github.com/YunoHost-Apps/invoiceninja5_ynh exists. However I don't have much spare time right now to work on this.

:'( so sad that invoiceninja can't be upgrade from 4 to 5 smoothly ...

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by rndmh3ro** [comment]
Awesome PR, @yalh76! Is it done in your opinion?

**Pull request merged**
