### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Level 0*

## Solution

- *Apply last example_ynh*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by rndmh3ro** [comment]
When testing the upgrade on my installation I encountered the following issue: https://github.com/invoiceninja/invoiceninja/issues/7070
We should probably uncomment the constants.php line in the upgrade/install script, too.

**Comment by yalh76** [comment]
> When testing the upgrade on my installation I encountered the following issue: [invoiceninja/invoiceninja#7070](https://github.com/invoiceninja/invoiceninja/issues/7070) We should probably uncomment the constants.php line in the upgrade/install script, too.

Done at [fix missing Constant.php](https://github.com/YunoHost-Apps/invoiceninja_ynh/pull/33/commits/9283c5a12a5594c34e431e6024c1c7dfe178f67b)

**Comment by yalh76** [comment]
!testme

**Review by rndmh3ro — APPROVED** [review]

**Comment by rndmh3ro** [comment]
I just got a cron mail:

```
Composer detected issues in your platform:

Your Composer dependencies require a PHP version ">= 7.4.0". You are running 7.3.33-4+0~20220627.98+debian11~1.gbp40b3e4.
```

The composer.json seems to be wrong.  Here's a dependency to 7.4: https://github.com/invoiceninja/invoiceninja/blob/v4.5.50/composer.lock#L10173

**Comment by yalh76** [comment]
!testme

**Pull request merged**
